spring:
  application:
    name: user-service
  datasource:
    # 数据库配置
    url: jdbc:mysql://localhost:3306/pawfinder_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        # 如果使用import方式，这些全局配置依然生效
        file-extension: yaml
  config:
    import:
      # 使用optional:前缀，即使Nacos配置缺失，应用也能启动
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension:yaml}

seata:
  enabled: true
  application-id: ${spring.application.name}
  # 核心配置 ↓↓↓
  service:
    vgroup-mapping:
      default_tx_group: default  # 这里必须配
    grouplist:
      default: 127.0.0.1:8091    # Seata 服务端地址，默认8091
  tx-service-group: default_tx_group  # 绑定分组