spring:
  application:
    name: pet-service
  datasource:
    # 数据库配置
    url: jdbc:mysql://localhost:3306/pawfinder_pet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123456
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 核心配置 ↓↓↓
  service:
    vgroup-mapping:
      default_tx_group: default  # 这里必须配
    grouplist:
      default: 127.0.0.1:8091    # Seata 服务端地址，默认8091
  tx-service-group: default_tx_group  # 绑定分组